### ISSUE TITLE
Docs: Include dayjs as a requirement

### ISSUE THREAD

**Issue by Namchee** [kenhyuwa/vue-tailwind-picker#10]
Based on #4 , `dayjs` is now a `peerDependency`. Due to this, users must install `dayjs` themselves.

However, the [documentation](https://vue-tailwind-picker.netlify.app/usage/) fails to address this requirement and states that only TailwindCSS is required.

**Comment by kenhyuwa** [comment]
Hello, 
I have update documentasion.
Thank you...
