### ISSUE TITLE
ask: dayjs is bundled

### ISSUE THREAD

**Issue by mazipan** [kenhyuwa/vue-tailwind-picker#4]
You can see https://bundlephobia.com/result?p=vue-tailwind-picker@1.1.0, the dayjs is become part of your library.
This means people might have different dayjs version in their project.
For this case, dayjs should become `peerDependencies`, not `dependencies`. We let users install their own dayjs.

But this is just my opinion, you might have your own reasons for this decision.

**Comment by kenhyuwa** [comment]
Thank you for suggestion,
I have moved dayjs & tailwindcss to `peerDependencies`
