### ISSUE TITLE
how to choose another date for weekend and holiday?

### ISSUE THREAD

**Issue by EliotRaven** [kenhyuwa/vue-tailwind-picker#5]
![image](https://user-images.githubusercontent.com/25608846/85565693-0c5bfb80-b638-11ea-9d62-9089a269e1f1.png)

For example
I want to use sat and sun as weekend
and week start from monday

is it real?

**Comment by EliotRaven** [comment]
and one more question, how to use multiple event in one day?

for example I wan't make 5 meetings today with my 5 different friends and in calendar will be cool see this 5 events and events counter in right-top position.

**Comment by kenhyuwa** [comment]
Oke, I add this feature for new release.
Thank you for suggestion feature.

**Comment by EliotRaven** [comment]
> Oke, I add this feature for new release.
> Thank you for suggestion feature.

thanks, when will be new release?)

**Comment by kenhyuwa** [comment]
I have released new version see [CHANGELOG](https://github.com/kenhyuwa/vue-tailwind-picker/blob/master/CHANGELOG.md#113)
