### ISSUE TITLE
Cannot select previous years

### ISSUE THREAD

**Issue by yaameen** [kenhyuwa/vue-tailwind-picker#7]
Year can only be selected from the current year on-wards. Cannot select previous years!

**Comment by kenhyuwa** [comment]
By default, date value is date now, then previous date is disabled
you can setting with props `startDate`
Thank you.

**Comment by yaameen** [comment]
Setting the startDate still does not allow you to select previous years.

Regardless it always start from 2020

**Comment by kenhyuwa** [comment]
I have released new version, see [CHANGELOG](https://github.com/kenhyuwa/vue-tailwind-picker/blob/master/CHANGELOG.md#113)

**Comment by qnox81** [comment]
I was trying to use with init prop set to false, but still i cannot go dates before now() date.

Is it possible to use it to f.e. enter born date like 1940-01-01?

```
<VueTailwindPicker
    :init="false"
    @change="(v) => born_date = v"
>
    <input id="born_date"
           name="born_date"
           v-model="born_date"
    />
</VueTailwindPicker>
```

**Comment by dansku** [comment]
For what I can see, I also can't select any date before the current one. 
It says it's fixed, I just can't find a way get it working. Any examples on this?
Thanks
