### ISSUE TITLE
Initial value setting

### ISSUE THREAD

**Issue by dukechill** [kenhyuwa/vue-tailwind-picker#8]
Hi, I want to know the way to set default date to empty value.

The default value always is the local day

Thank you

**Comment by kenhyuwa** [comment]
Hi,
default value for date is now.
if you want to request for empty date default,
next release, i add this feature with new props `init`.
thank you.

**Comment by kenhyuwa** [comment]
hello, check new release on CHANGELOG.
thank you.

**Comment by dukechill** [comment]
Nice feature and nice work
Thank you
